from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from datetime import datetime
import psycopg2

class Ui_check(object):
    """
    cuando instancies una clase de tipo Ui_check
    le tienes que pasar el rut como argumento
    por ejemplo:
    win = Ui_check(rut)
    """
    def __init__(self,rutMedico, rut, name, fecha, edad, preS, tramo):
        self.rutMedico = str(rutMedico)
        self.rut = str(rut)
        self.name = str(name)
        self.fecha = str(fecha)
        self.edaad = str(edad)
        self.preS = str(preS)
        self.tramoo = str(tramo)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        self.radioPressed = False
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(200, 20, 300, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.nombrePaciente = QtWidgets.QLabel(self.centralwidget)
        self.nombrePaciente.setGeometry(QtCore.QRect(60, 60, 51, 31))
        self.nombrePaciente.setObjectName("nombrePaciente")
        self.edadPaciente = QtWidgets.QLabel(self.centralwidget)
        self.edadPaciente.setGeometry(QtCore.QRect(60, 210, 41, 31))
        self.edadPaciente.setObjectName("edadPaciente")
        self.tramo = QtWidgets.QLabel(self.centralwidget)
        self.tramo.setGeometry(QtCore.QRect(60, 310, 47, 31))
        self.tramo.setObjectName("tramo")
        self.fechaNacimiento = QtWidgets.QLabel(self.centralwidget)
        self.fechaNacimiento.setGeometry(QtCore.QRect(60, 160, 131, 31))
        self.fechaNacimiento.setObjectName("fechaNacimiento")
        self.prevSocial = QtWidgets.QLabel(self.centralwidget)
        self.prevSocial.setGeometry(QtCore.QRect(60, 260, 111, 31))
        self.prevSocial.setObjectName("prevSocial")
        self.rutPaciente = QtWidgets.QLabel(self.centralwidget)
        self.rutPaciente.setGeometry(QtCore.QRect(60, 110, 31, 31))
        self.rutPaciente.setObjectName("rutPaciente")
        self.outputNombre = QtWidgets.QLabel(self.centralwidget)
        self.outputNombre.setGeometry(QtCore.QRect(126, 60, 361, 31))
        self.outputNombre.setText("")
        self.outputNombre.setObjectName("outputNombre")
        self.outputRut = QtWidgets.QLabel(self.centralwidget)
        self.outputRut.setGeometry(QtCore.QRect(116, 110, 231, 31))
        self.outputRut.setText("")
        self.outputRut.setObjectName("outputRut")
        self.outputFechaNac = QtWidgets.QLabel(self.centralwidget)
        self.outputFechaNac.setGeometry(QtCore.QRect(200, 162, 171, 31))
        self.outputFechaNac.setText("")
        self.outputFechaNac.setObjectName("outputFechaNac")
        self.outputEdad = QtWidgets.QLabel(self.centralwidget)
        self.outputEdad.setGeometry(QtCore.QRect(110, 212, 141, 31))
        self.outputEdad.setText("")
        self.outputEdad.setObjectName("outputEdad")
        self.outputPrevSocial = QtWidgets.QLabel(self.centralwidget)
        self.outputPrevSocial.setGeometry(QtCore.QRect(170, 262, 171, 31))
        self.outputPrevSocial.setText("")
        self.outputPrevSocial.setObjectName("outputPrevSocial")
        self.outputTramo = QtWidgets.QLabel(self.centralwidget)
        self.outputTramo.setGeometry(QtCore.QRect(130, 313, 131, 31))
        self.outputTramo.setText("")
        self.outputTramo.setObjectName("outputTramo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 390, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.ingresarCheck)
        self.descripcionChequeo = QtWidgets.QTextEdit(self.centralwidget)
        self.descripcionChequeo.setGeometry(QtCore.QRect(400, 110, 261, 191))
        self.descripcionChequeo.setObjectName("descripcionChequeo")
        self.descripcion = QtWidgets.QLabel(self.centralwidget)
        self.descripcion.setGeometry(QtCore.QRect(490, 60, 71, 31))
        self.descripcion.setObjectName("descripcion")
        self.hospitalizar = QtWidgets.QLabel(self.centralwidget)
        self.hospitalizar.setGeometry(QtCore.QRect(490, 320, 91, 31))
        self.hospitalizar.setObjectName("hospitalizar")
        self.botonSi = QtWidgets.QRadioButton(self.centralwidget)
        self.botonSi.setGeometry(QtCore.QRect(470, 360, 41, 17))
        self.botonSi.setObjectName("botonSi")
        self.botonNo = QtWidgets.QRadioButton(self.centralwidget)
        self.botonNo.setGeometry(QtCore.QRect(550, 360, 41, 17))
        self.botonNo.setObjectName("botonNo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.outputNombre.setText(str(self.name))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.group = QButtonGroup()
        self.group.addButton(self.botonSi)
        self.group.setId(self.botonSi, 1)
        self.group.addButton(self.botonNo)
        self.group.setId(self.botonNo, 0)
        self.botonSi.clicked.connect(lambda: self.botonPresionado(self.group))
        self.botonNo.clicked.connect(lambda: self.botonPresionado(self.group))
        self.outputNombre.setText(self.name)
        self.outputRut.setText(self.rut)
        self.outputFechaNac.setText(self.fecha)
        self.outputEdad.setText(self.edaad)
        self.outputPrevSocial.setText(self.preS)
        self.outputTramo.setText(self.tramoo)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ingresar chequeo inicial"))
        self.titulo.setText(_translate("MainWindow", "Ingresar chequeo inicial"))
        self.nombrePaciente.setText(_translate("MainWindow", "Nombre:"))
        self.edadPaciente.setText(_translate("MainWindow", "Edad:"))
        self.tramo.setText(_translate("MainWindow", "Tramo:"))
        self.fechaNacimiento.setText(_translate("MainWindow", "Fecha de nacimiento:"))
        self.prevSocial.setText(_translate("MainWindow", "Previsión social:"))
        self.rutPaciente.setText(_translate("MainWindow", "Rut:"))
        self.pushButton.setText(_translate("MainWindow", "Ingresar"))
        self.descripcion.setText(_translate("MainWindow", "Descripción"))
        self.hospitalizar.setText(_translate("MainWindow", "¿Hospitalizar?"))
        self.botonSi.setText(_translate("MainWindow", "Sí"))
        self.botonNo.setText(_translate("MainWindow", "No"))

    def botonPresionado(self, group):
        self.radioPressed = True
        self.id = group.checkedId()
    def ingresarCheck(self):
        self.descCheck = self.descripcionChequeo.toPlainText()
        if self.radioPressed == True:
            try:
                connection = psycopg2.connect(user="bdi2018f",password="bdi2018f",host="bdd.inf.udec.cl",database="bdi2018f",port=5432)
                cursor = connection.cursor()
                if self.id == 1:
                    cursor.execute("INSERT INTO ing.chequeo_inicial (rut, descripcion, estado) VALUES(%s, %s, True)", (self.rutMedico, self.descCheck,))
                    cursor.execute("INSERT INTO ing.pasa (rut) VALUES(%s)", (self.rut,))
                    cursor.execute("INSERT INTO ing.historial (fecha_ingreso, hora_ingreso) VALUES('2019-10-06', '18:30:45')")
                    cursor.execute("INSERT INTO ing.historial_paciente (rut) VALUES (%s)", (self.rut,))
                elif self.id == 0:
                    cursor.execute("INSERT INTO ing.chequeo_inicial (rut, descripcion, estado) VALUES(%s, %s, False)", (self.rutMedico, self.descCheck,))
                    cursor.execute("INSERT INTO ing.pasa (rut) VALUES(%s)", (self.rut,))
                    cursor.execute("INSERT INTO ing.historial (fecha_ingreso, hora_ingreso, fecha_alta, hora_alta) VALUES('2019-10-06', '18:30:45','2019-10-06', '18:30:45')")
                    cursor.execute("INSERT INTO ing.historial_paciente (rut) VALUES (%s)", (self.rut,))
                cursor.close()
                connection.commit()
            except Exception as e:
                print(e)
"""
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana = QtWidgets.QMainWindow()
    loginFrame = Ui_check("1","1","1","1","1","1")
    loginFrame.setupUi(ventana)
    ventana.show()
    sys.exit(app.exec_())
"""